install:
- wget https://github.com/gohugoio/hugo/releases/hugo_extended_0.55.6_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- hugo version
before_script: 
- rm -rf public
script:
- hugo
branches: 
 only:
 - master